package com.ingramcontent.dataverse.helper;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomLogger implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomLogger() {
    }

    


}